backstage/urls.py
from django.conf.urls.static import static
from django.template.defaulttags import url

from blog.urls import app_name
from ulife import settings
from . import views
from django.urls import path

app_name = 'backstage'

# url路由配置
urlpatterns = [
    # path Django2.0语法 兼容2.0以下版本 参数1：访问路径，参数2：视图函数
    path('index/', views.index, name='index'),
    path('login/', views.loginUser, name='loginUser'),
    path('userList/', views.UserListView.as_view(), name='userList'),
    path('findUser/', views.findUser, name='findUser'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('productList/', views.ProductListView.as_view(), name='productList'),
    path('categoryList/', views.CategoryListView.as_view(), name='categoryList'),
    path('productOrderList/', views.ProductOrderListView.as_view(), name='productOrderList'),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('upload_avatar/', views.upload_avatar, name='upload_avatar'),
    path('static/', views.upload_avatar, name='upload_avatar'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = views.page_not_found

blog/urls.py
from django.conf.urls import url
from blog.feeds import AllPostsRssFeed
from . import views
from django.urls import include
# 视图函数命名空间
app_name = 'blog'

# url路由配置
urlpatterns = [
    # path Django2.0语法 兼容2.0以下版本 参数1：访问路径，参数2：视图函数
    # path('', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

ulife/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from ulife import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),
                  path('', include('comments.urls')),
                  path('users/', include('users.urls')),
                  path('users/', include('django.contrib.auth.urls')),
                  path('backstage/', include('backstage.urls')),
                  path('static/<path:path>', serve, {"document_root": settings.STATIC_ROOT}),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^index/', views.index, name='index'),
    url(r'^loginUser/', views.loginUser, name='loginUser'),
    url(r'^loginIndex/', views.loginIndex, name='loginIndex'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    nickname = models.CharField(max_length=50, blank=True)
    user_type = models.CharField(max_length=20,default=0,blank=False)
    images_url = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=18,blank=False,default='')
    class Meta(AbstractUser.Meta):
        ordering = ['id']
        pass

backstage/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")

backstage/views.py
import os

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, render_to_response

from users.models import User
from backstage.models import MallProduct, MallProductCategory, MallProductOrder
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.db import connection

# def page_not_found(request):
#     return render_to_response('404.html')
def upload_avatar(request):
    file_obj = request.FILES.get('img')
    file_path = os.path.join('static/backstage/images/user', file_obj.name)
    with open(file_path, 'wb') as f:
        for chunk in file_obj.chunks():
            f.write(chunk)
        return render(request, 'backstage/my_profile.html',context={'img': file_path})


def signin(request):
    return render(request, 'backstage/signin.html')


def signup(request):
    return render(request, 'backstage/signup.html')


@login_required()
def myprofile(request):
    return render(request, 'backstage/my_profile.html')


@login_required
# request参数必须有，封装用户所有请求内容
def index(request):
    # 不能直接返回字符串，django的规范必须用HttpResponse封装。
    return render(request, 'backstage/index.html')


def loginUser(request):
    return render(request, 'backstage/login.html')


@login_required
def userList(request):
    list = User.objects.all()
    page = Paginator(list, 1)
    print(page)
    print(page.count)
    print(page.num_pages)
    return render(request, 'backstage/user_list.html', context={'user_list': list})


def findUser(request):
    ctx = {}
    if request.POST:
        if request.POST['username']:
            ctx['username'] = request.POST['username']
        if request.POST['nickname']:
            ctx['nickname'] = request.POST['nickname']
    if ctx.__len__() < 1:
        return HttpResponse('失败')
    user = User.objects.filter(**ctx)
    message = '0'
    if user.count() > 0:
        message = '查询成功'
    return render(request, 'backstage/user-detail.html', context={'users': user, 'message': message})


# 类视图 必须继承一个view
class UserListView(LoginRequiredMixin, ListView):
    # 指定要使用的模型
    model = User
    # 使用的模版
    template_name = 'backstage/user_list.html'
    # 模型列表数据变量名
    context_object_name = 'user_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 5

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        # 打印sql语句
        print(connection.queries)

        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


# 类视图 必须继承一个view
class ProductListView(LoginRequiredMixin, ListView):
    # 指定要使用的模型
    model = MallProduct
    # 使用的模版
    template_name = 'backstage/product_list.html'
    # 模型列表数据变量名
    context_object_name = 'user_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 10

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)
        context['categorys'] = MallProductCategory.objects.all()

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。

        # 打印sql语句
        print(connection.queries)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码

templates/backstage/left.html
<body>
<div class="leftpanel" style='position:fixed; z-index:999;'>
    <div class="media profile-left">
        <a class="pull-left profile-thumb" href="profile.html">
            {#            头像地址#}
            <img class="img-circle" src="/static/backstage/images/user/awdad1w5d15.png" alt="">
        </a>
        <div class="media-body">
            <h4 class="media-heading">{{ user.username }}</h4>
            <span class="user-options"><a href="{% url 'backstage:myprofile' %}"><i class="glyphicon glyphicon-user"></i></a>
                              <a href="#"><i class="glyphicon glyphicon-envelope"></i></a>
                              <a href="#"><i class="glyphicon glyphicon-cog"></i></a>
                              <a href="{% url 'logout' %}?next={{ request.path }}"><i class="glyphicon glyphicon-log-out"></i></a>
							</span>
        </div>
    </div><!-- media -->


    <ul class="nav nav-pills nav-stacked">
        <li class="active">
            {#            {% if request.user.usertype == '0' %}#}
            <a href="{% url 'backstage:index' %}"><i class="fa fa-home"></i> <span>首页</span></a></li>
        {#            {% endif %}#}

        <li>
            {#            {% if request.user.usertype == '0' %}#}
            <a href="{% url 'backstage:userList' %}"><i class="fa fa-bar-chart-o"></i> <span>用户列表</span></a>
            {#            {% endif %}#}
        </li>
        <li class="parent"><a href="#"><i class="fa fa-list-ul"></i> <span>商品</span></a>
            <ul class="children">
                <li><a href="{% url 'backstage:productList' %}"><i class="fa fa-briefcase"></i>&nbsp;&nbsp;&nbsp; <span>商品列表</span></a></li>
                <li><a href="{% url 'backstage:categoryList' %}"><i class="fa fa-briefcase"></i>&nbsp;&nbsp;&nbsp; <span>分&nbsp;&nbsp;类</span></a></li>
                <li><a href="{% url 'backstage:productOrderList' %}"><i class="fa fa-briefcase"></i>&nbsp;&nbsp;&nbsp; <span>商品订单列表</span></a></li>
            </ul>
        </li>
    </ul>
</div><!-- leftpanel -->

</body>

templates/backstage/login.html
<!DOCTYPE html>
<html>

<head>
    <title>Trendy Login Forms in Flat Design</title>

    <link href="/static/backstage/css/login/style.css" rel='stylesheet' type='text/css'/>

    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>

    <!--webfonts-->
    <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic|Oswald:400,300,700'
          rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,700,800'
          rel='stylesheet' type='text/css'>
    <!--//webfonts-->

</head>
<body bgcolor="#faebd7">
<div class="login-form" >
    <div class="first-login">
        <form>
            <li>
                <input type="text" class="text" value="Name" onFocus="this.value = '';"
                       onBlur="if (this.value == '') {this.value = 'Name';}"><a href="#" class=" icon user"></a>
            </li>
            <li class="pw">
                <input type="password" value="Password" onFocus="this.value = '';"
                       onBlur="if (this.value == '') {this.value = 'Password';}"><a href="#" class=" icon lock"></a>
            </li>
            <div class="submit">
                <input type="submit" onClick="myFunction()" value="LOG IN">
            </div>
        </form>
    </div>
</div>

</body>
</html>

templates/backstage/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Alpha - Bootstrap Admin Template</title>

    <link href="/static/backstage/css/style.default.css" rel="stylesheet">

</head>

<body class="signin">


<section>

    <div class="panel panel-signin">
        <div class="panel-body">
            {% if msg %}
                <div class="alert alert-success" id="msg">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>{{ msg }}</strong> 欢迎您的加入。
                </div>
            {% else %}
                <h4 class="text-center mb5">已创建账号?</h4>
                <p class="text-center">登录您的账号</p>
            {% endif %}
            <div class="logo text-center">
                {#                        <img src="/static/backstage/picture/logo-primary.png" alt="Alpha Logo" >#}
            </div>
            <br/>

            <div class="mb30"></div>

            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                <div class="input-group mb15">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <input type="text" class="form-control" name="username" placeholder="用户名">
                </div><!-- input-group -->
                <div class="input-group mb15">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <input type="password" class="form-control" name="password" placeholder="密码">
                </div><!-- input-group -->
                <input type="hidden" name="next" value="{% url 'backstage:index' %}">
                <div class="clearfix">
                    <div class="pull-left">
                        <div class="ckbox ckbox-primary mt10">
                            <input type="checkbox" id="rememberMe" value="1">
                            <label for="rememberMe">记住我</label>
                        </div>
                    </div>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-success">登录 <i class="fa fa-angle-right ml5"></i></button>
                    </div>
                </div>
            </form>
        </div><!-- panel-body -->
        <div class="panel-footer">
            <a href="{% url 'users:register' %}?next={{ request.path }}" class="btn btn-primary btn-block">没有账户?
                现在创建账户。</a>
        </div><!-- panel-footer -->
    </div><!-- panel -->
</section>


<script src="/static/backstage/js/jquery-1.11.1.min.js"></script>
<script src="/static/backstage/js/jquery-migrate-1.2.1.min.js"></script>
<script src="/static/backstage/js/bootstrap.min.js"></script>
<script src="/static/backstage/js/modernizr.min.js"></script>
<script src="/static/backstage/js/pace.min.js"></script>
<script src="/static/backstage/js/retina.min.js"></script>
<script src="/static/backstage/js/jquery.cookies.js"></script>

<script src="/static/backstage/js/custom.js"></script>

</body>
</html>

templates/backstage/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Alpha - Bootstrap Admin Template</title>

    <link href="/static/backstage/css/style.default.css" rel="stylesheet">

</head>

<body class="signin">

<section>

    <div class="panel panel-signup">
        <div class="panel-body">
            <div class="logo text-center">
                <img src="/static/backstage/picture/logo-primary.png" alt="Alpha Logo">
            </div>
            <br/>
            <h4 class="text-center mb5">Create a new account</h4>
            <p class="text-center">Please enter your credentials below</p>

            <div class="mb30"></div>

            <form class="form" action="{% url 'users:register' %}" method="post" name="register-form"
            onsubmit="submitForm()">
                {% csrf_token %}
                <div class="col-sm-6">
                    <div class="input-group mb15">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input type="text" class="form-control" placeholder="输入用户名" name="username">
                    </div><!-- input-group -->
                </div>
                <div class="col-sm-6">
                    <div class="input-group mb15">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input type="password" class="form-control" placeholder="输入密码" name="password1">
                    </div><!-- input-group -->
                </div>
                <div class="col-sm-6">
                    <div class="input-group mb15">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                        <input type="email" class="form-control" placeholder="输入邮箱" name="email">
                    </div><!-- input-group -->
                </div>
                <div class="col-sm-6">
                    <div class="input-group mb15">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input type="password" class="form-control" placeholder="再次输入密码" name="password2">
                    </div><!-- input-group -->
                </div>
                <div class="clearfix">
                    <div class="pull-left">
                        <div class="ckbox ckbox-primary mt5">
                            <input type="checkbox" id="agree" value="1">
                            <a href="#">已阅读并接受</a></label>
                        </div>
                    </div>
                    <input type="hidden" name="next" value="backstage/index">
                    <div class="pull-right">
                        <button class="btn btn-success">创建账户</button>
                    </div>
                </div>
            </form>

        </div><!-- panel-body -->
        <div class="panel-footer">
            <a href="signin.html" class="btn btn-primary btn-block">Already a Member? Sign In</a>
        </div><!-- panel-footer -->
    </div><!-- panel -->

</section>

<script src="/static/backstage/js/jquery-1.11.1.min.js"></script>
<script src="/static/backstage/js/jquery-migrate-1.2.1.min.js"></script>
<script src="/static/backstage/js/bootstrap.min.js"></script>
<script src="/static/backstage/js/modernizr.min.js"></script>
<script src="/static/backstage/js/pace.min.js"></script>
<script src="/static/backstage/js/retina.min.js"></script>
<script src="/static/backstage/js/jquery.cookies.js"></script>

<script src="/static/backstage/js/custom.js"></script>

</body>
</html>