backstage/urls.py
from django.conf.urls.static import static
from django.template.defaulttags import url

from blog.urls import app_name
from ulife import settings
from . import views
from django.urls import path

app_name = 'backstage'

# url路由配置
urlpatterns = [
    # path Django2.0语法 兼容2.0以下版本 参数1：访问路径，参数2：视图函数
    path('index/', views.index, name='index'),
    path('login/', views.loginUser, name='loginUser'),
    path('userList/', views.UserListView.as_view(), name='userList'),
    path('findUser/', views.findUser, name='findUser'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('productList/', views.ProductListView.as_view(), name='productList'),
    path('categoryList/', views.CategoryListView.as_view(), name='categoryList'),
    path('productOrderList/', views.ProductOrderListView.as_view(), name='productOrderList'),
    path('myprofile/', views.myprofile, name='myprofile'),
    path('upload_avatar/', views.upload_avatar, name='upload_avatar'),
    path('static/', views.upload_avatar, name='upload_avatar'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = views.page_not_found

blog/urls.py
from django.conf.urls import url
from blog.feeds import AllPostsRssFeed
from . import views
from django.urls import include
# 视图函数命名空间
app_name = 'blog'

# url路由配置
urlpatterns = [
    # path Django2.0语法 兼容2.0以下版本 参数1：访问路径，参数2：视图函数
    # path('', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

ulife/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from ulife import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),
                  path('', include('comments.urls')),
                  path('users/', include('users.urls')),
                  path('users/', include('django.contrib.auth.urls')),
                  path('backstage/', include('backstage.urls')),
                  path('static/<path:path>', serve, {"document_root": settings.STATIC_ROOT}),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^index/', views.index, name='index'),
    url(r'^loginUser/', views.loginUser, name='loginUser'),
    url(r'^loginIndex/', views.loginIndex, name='loginIndex'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    nickname = models.CharField(max_length=50, blank=True)
    user_type = models.CharField(max_length=20,default=0,blank=False)
    images_url = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=18,blank=False,default='')
    class Meta(AbstractUser.Meta):
        ordering = ['id']
        pass

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import User


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email","nickname","user_type","phone",)

users/views.py
from django.contrib import auth
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse
from django.urls import reverse

from .forms import RegisterForm


def register(request):
    # 从 get 或者 post 请求中获取 next 参数值
    # get 请求中，next 通过 url 传递，即 /?next=value
    # post 请求中，next 通过表单传递，即 <input type="hidden" name="next" value="{{ next }}"/>
    redirect_to = request.POST.get('next', request.GET.get('next', ''))
    # 只有当请求为 POST 时，才表示用户提交了注册信息
    if request.method == 'POST':
        # request.POST 是一个类字典数据结构，记录了用户提交的注册信息
        # 这里提交的就是用户名（username）、密码（password）、确认密码、邮箱（email）
        # 用这些数据实例化一个用户注册表单
        form = RegisterForm(request.POST)

        # 验证数据的合法性
        if form.is_valid():
            # 如果提交数据合法，调用表单的 save 方法将用户数据保存到数据库
            form.save()
            return render(request, 'users/signin.html', context={'msg': '注册成功'})
        else:
            return render(request, 'users/signup.html', context={'form': form, 'next': redirect_to,'error_messages':form._errors})
    else:
        # 请求不是 POST，表明用户正在访问注册页面，展示一个空的注册表单给用户
        form = RegisterForm()

    # 渲染模板
    # 如果用户正在访问注册页面，则渲染的是一个空的注册表单
    # 如果用户通过表单提交注册信息，但是数据验证不合法，则渲染的是一个带有错误信息的表单
    # 将记录用户注册前页面的 redirect_to 传给模板，以维持 next 参数在整个注册流程中的传递
    return render(request, 'users/signup.html', context={'form': form, 'next': redirect_to})


def index(request):
    return render(request, 'index.html')

def loginIndex(request):
    return render(request, 'users/signin.html')

def loginUser(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    login_form = RegisterForm(request.POST)
    if login_form.is_valid:
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            # 如果登入成功，重定向要主页
            return HttpResponseRedirect(reverse('backstage:index'))
        else:
            # user为None，说明账号或密码错误
            return render(request, "users/signin.html", {"msg": "用户名或密码错误"})
    else:
        # 表单无效，返回login_form对象即可，在template调用login_form.errors这个字典去获取相关的错误
        return render(request, "users/signin.html", {"login_form": login_form})

templates/users/signin.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Alpha - Bootstrap Admin Template</title>

    <link href="{% static '/backstage/css/style.default.css' %}" rel="stylesheet">
{#    <link href="static/backstage/css/style.default.css" rel="stylesheet">#}
</head>

<body class="signin">
<section>
    <div class="panel panel-signin">
        <div class="panel-body">
            {% if msg %}
                <div class="alert alert-success" id="msg">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>{{ msg }}</strong>
                </div>
            {% else %}
                <h4 class="text-center mb5">已创建账号?</h4>
                <p class="text-center">登录您的账号</p>
            {% endif %}
            <div class="logo text-center">
                {#                        <img src="/static/backstage/picture/logo-primary.png" alt="Alpha Logo" >#}
            </div>
            <br/>

            <div class="mb30"></div>

            <form action="{% url 'users:loginUser' %}" method="post">
                {% csrf_token %}
                <div class="input-group mb15">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <input type="text" class="form-control" name="username" placeholder="用户名">
                </div><!-- input-group -->
                <div class="input-group mb15">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <input type="password" class="form-control" name="password" placeholder="密码">
                </div><!-- input-group -->
                <input type="hidden" name="next" value="{% url 'backstage:index' %}">
                <div class="clearfix">
                    <div class="pull-left">
                        <div class="ckbox ckbox-primary mt10">
                            <input type="checkbox" id="rememberMe" value="1">
                            <label for="rememberMe">记住我</label>
                        </div>
                    </div>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-success">登录 <i class="fa fa-angle-right ml5"></i></button>
                    </div>
                </div>
            </form>
        </div><!-- panel-body -->
        <div class="panel-footer">
            <a href="{% url 'users:register' %}?next={{ request.path }}" class="btn btn-primary btn-block">没有账户?
                现在创建账户。</a>
        </div><!-- panel-footer -->
    </div><!-- panel -->
</section>


<script src="{% static '/backstage/js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static '/backstage/js/jquery-migrate-1.2.1.min.js' %}"></script>
<script src="{% static '/backstage/js/bootstrap.min.js' %}"></script>
<script src="{% static '/backstage/js/modernizr.min.js' %}"></script>
<script src="{% static '/backstage/js/pace.min.js' %}"></script>
<script src="{% static '/backstage/js/retina.min.js' %}"></script>
<script src="{% static '/backstage/js/jquery.cookies.js' %}"></script>

<script src="{% static '/backstage/js/custom.js' %}"></script>

</body>
</html>

templates/users/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Alpha - Bootstrap Admin Template</title>

    <link href="/static/backstage/css/style.default.css" rel="stylesheet">

</head>

<body class="signin">

<section>

    <div class="panel panel-signup">
        <div class="panel-body">
            <div class="logo text-center">
                <img src="/static/backstage/picture/logo-primary.png" alt="Alpha Logo">
            </div>
            <br/>
            <h4 class="text-center mb5">创建一个账户</h4>
            <p class="text-center">输入重要的信息，您可以通过邮箱登录。</p>
            {% if error_messages %}
                {% for k,v in error_messages.items %}
                    <div class="alert alert-danger" id="msg">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>{{ v }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="mb30"></div>

            <form class="form" action="{% url 'users:register' %}" method="post" name="register-form"
                  onsubmit="submitForm()">
                {% csrf_token %}
                <div class="col-sm-6">
                    <div class="input-group mb15">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input type="text" class="form-control" placeholder="输入用户名" name="username">
                        <input type="hidden" name="user_type" value="0">
                    </div><!-- input-group -->
                </div>
                <div class="col-sm-6">
                    <div class="input-group mb15">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input type="password" class="form-control" placeholder="输入密码" name="password1">
                    </div><!-- input-group -->
                </div>
                <div class="col-sm-6">
                    <div class="input-group mb15">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                        <input type="email" class="form-control" placeholder="输入邮箱" name="email">
                    </div><!-- input-group -->
                </div>
                <div class="col-sm-6">
                    <div class="input-group mb15">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input type="password" class="form-control" placeholder="再次输入密码" name="password2">
                    </div><!-- input-group -->
                </div>
                <div class="col-sm-6">
                    <div class="input-group mb15">
                        <span class="input-group-addon"><i class="fa fa-heart"></i></span>
                        <input type="text" class="form-control" placeholder="昵称" name="nickname">
                    </div><!-- input-group -->
                </div>
                <div class="col-sm-6">
                    <div class="input-group mb15">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
                        <input type="text" class="form-control" placeholder="手机号" name="phone">
                    </div><!-- input-group -->
                </div>
                <div class="clearfix">
                    <div class="pull-left">
                        <div class="ckbox ckbox-primary mt5">
                            <input type="checkbox" id="agree" value="1">
                            <label for="agree">我已接受 <a href="#">条款。</a></label>
                        </div>
                    </div>
                    <input type="hidden" name="next" value="backstage/index">
                    <div class="pull-right">
                        <button class="btn btn-success">创建账户</button>
                    </div>
                </div>
            </form>

        </div><!-- panel-body -->
        <div class="panel-footer">
            <a href="{% url 'users:loginIndex' %}" class="btn btn-primary btn-block">已经注册过了？去登录</a>
        </div><!-- panel-footer -->
    </div><!-- panel -->

</section>

<script src="/static/backstage/js/jquery-1.11.1.min.js"></script>
<script src="/static/backstage/js/jquery-migrate-1.2.1.min.js"></script>
<script src="/static/backstage/js/bootstrap.min.js"></script>
<script src="/static/backstage/js/modernizr.min.js"></script>
<script src="/static/backstage/js/pace.min.js"></script>
<script src="/static/backstage/js/retina.min.js"></script>
<script src="/static/backstage/js/jquery.cookies.js"></script>

<script src="/static/backstage/js/custom.js"></script>

</body>
</html>